#! /bin/sh
# variables for use
export BROWSER="chromium"
export EDITOR="vim"
export PATH="$PATH:$HOME/bin"

### android build variables ###
export USE_CCACHE=1
export CCACHE_DIR=~/.ccache

eval $(dircolors -b ~/.dircolors)
