#! /bin/sh
# aliases for all shells

alias ls='ls --color=auto'
alias grep='grep --color=auto'
alias EWS='ssh jankaus2@remlnx.ews.illinois.edu'
alias cdh='urxvt -cd $(pwd) &'
alias sys='sudo systemctl'
