#!/bin/bash
# Based on a script by Zach Holman.

# import functions
# change directories to be in the same one as the executable (in case we aren't already there)
cd `dirname $0`> /dev/null
DIR=$PWD
source "$DIR/install_lib"

# LINK_MAP usage
# 'file:link'
# This is a map from files in the project, to where
# a softlink is placed in the destination (defined below)
# file names are realative to the project directory and
# like names are realative to the user defined folder
LINK_MAP=(
          'gitconfig:.gitconfig'
          'gitignore:.gitignore'
          'vimrc:.vimrc'
          'vim:.vim'
          'xmobarrc:.xmobarrc'
          'xmonad:.xmonad'
          'zshrc:.zshrc'
          'zsh:.zsh'
          'bashrc:.bashrc'
          'commonsh:.commonsh'
          'dircolors:.dircolors'
          'xmod:.Xmodmap'
          'Xdefaults:.Xdefaults'
          'lock:bin/lock'
          'volume:bin/volume'
          'fonts:.fonts'
          )

# Script will check to see if these files are in the current PATH and output if
# any are not found
IMPORTANT_PROGRAMS=(
    'zsh'
    'startx'
    'xmonad'
    'xmobar'
    'git'
    'vim'
    )

# the root of where you want the links to show up
DEST="$HOME"


set -e

echo ''


#TODO this could be more robust
if [ "$1" = "-h" ]
then
    print_usage
    exit 0
fi

# need the realative directory of this file to the user's home folder
REL_DIR="${DIR#"$DEST/"}"

overwrite_all=false
backup_all=false
skip_all=false

info 'installing dotfiles'

for str in ${LINK_MAP[@]}; do


  # TODO tear out a lot of this.
  # use ln -s -r -b instead
    # Determine the file pointed to and the name of the link
    file=${str%:*}
    #echo "link = ${str#*:}"
    link=${str#*:}

    ### Find Depth
    # determine the depth of the link destination
    _tmp="${link//[^\/]}"
    _depth=${#_tmp}
    FILE_PATH="$REL_DIR/$file"
    for ((i=0; i<$_depth; i++))
    do
        FILE_PATH="../$FILE_PATH"
    done
    link="$DEST/$link"

    mkdir -p $(dirname $link)

    #rename variables
    src=$FILE_PATH
    dest=$link

    if [ -f $dest ] || [ -d $dest ]
    then

      overwrite=false
      backup=false
      skip=false

      if [ "$overwrite_all" == "false" ] && [ "$backup_all" == "false" ] && [ "$skip_all" == "false" ]
      then
        user "File already exists: `basename $src`, what do you want to do? [s]kip, [S]kip all, [o]verwrite, [O]verwrite all, [b]ackup, [B]ackup all?"
        read -n 1 action

        case "$action" in
          o )
            overwrite=true;;
          O )
            overwrite_all=true;;
          b )
            backup=true;;
          B )
            backup_all=true;;
          s )
            skip=true;;
          S )
            skip_all=true;;
          * )
            ;;
        esac
      fi

      if [ "$overwrite" == "true" ] || [ "$overwrite_all" == "true" ]
      then
        rm -rf $dest
        success "removed $dest"
      fi

      if [ "$backup" == "true" ] || [ "$backup_all" == "true" ]
      then
        mv $dest $dest\.backup
        success "moved $dest to $dest.backup"
      fi

      if [ "$skip" == "false" ] && [ "$skip_all" == "false" ]
      then
        link_files $src $dest
      else
        success "skipped $src"
      fi

    else
      link_files $src $dest
    fi

done

echo "checking installed programs"

for prog in ${IMPORTANT_PROGRAMS[@]}; do
    check_in_path $prog
done

fc-cache -f ~/.fonts
install_Vundle

echo ""
echo "done"
