#!/bin/bash

# font configuration
bold=$(tput bold)
normal=$(tput sgr0)

#basic usage
print_usage(){
    echo "$0: links your dofiles from your home folder to this project
$0 [-h]
* Make sure that this script stays in the folder that it came in (should be the
      main directory for the project).
* links are realative (they don't start from root)
* if you move this folder, all the links will break

-h    print this help and then exits
        "
}


# print helpers
info () {
  printf "\r  [ \033[00;34m..\033[0m ] $1"
}

user () {
  printf "\r  [ \033[0;33m?\033[0m ] $1 "
}

success () {
  printf "\r\033[2K  [ \033[00;32mOK\033[0m ] $1\n"
}

warn () {
  printf "\r\033[2K  [\033[0;33mWARNING\033[0m] $1\n"
}

fail () {
  printf "\r\033[2K  [\033[0;31mFAIL\033[0m] $1\n"
  echo ''
  exit
}

link_files () {
  ln -s $1 $2
  success "linked $1 to $2"
}

check_cmd() {
    return $(type $1 > /dev/null 2>&1)
}

check_in_path () {
    check_cmd $1 || warn $bold$1$normal" was not found in PATH"
}

install_Vundle() {
    if (check_cmd git) && (check_cmd vim)
    then
        git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim
        vim +PluginInstall +qall
    else
        warn "git and vim are required to install Vundle"
        info "git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim"
        info "vim +PluginInstall +qall"
    fi
}
